### PR TITLE
Activate zef upload feature

### PR DESCRIPTION
**Pull request by lizmat**
The files were in the repo already, but not mentioned in the META

### CODE REVIEW

**Comment by lizmat** [comment]
I have no idea why the test actions failed: "fez" just lives in the ecosystem ??

**Comment by skaji** [comment]
* zef bundled with rakudo 2020.05.1 does not recognize "fez" ecosystem
* fez module is in "fez" ecosystem

So workflows of rakudo 2020.05.1 fail.

**Comment by lizmat** [comment]
I'm not sure I understand your comment.

Are you saying that we cannot have upload to zef on 2021.10 because it fails on 2020.05?  Or that you feel that "fez" should be uploaded to CPAN as well, to allow it to work on versions like 2020.05 and earlier?

**Comment by skaji** [comment]
Because you said "I have no idea why the test actions failed", I just tried to explain why it failed.

**Comment by lizmat** [comment]
Ah, ok, understood  :-)

**Comment by lizmat** [comment]
Meanwhile, one still cannot upload to the zef ecosystem with an App::Mi6 that comes out of the box.  :-(   It would be nice if we could make an advent post about moving to the zef ecosystem  :-)

**Comment by skaji** [comment]
@lizmat  Thank you for your patience. I've just released mi6 version 2.0.0.

**Pull request merged**
