### PR TITLE
Add a build-readme command

### PR DESCRIPTION
**Pull request by Skarsnik**
To just regenerate the Readme.md

### CODE REVIEW

**Comment by shoichikaji** [comment]
Thank you for the pull request.

mi6 build/test regenerates README.md,
so I'm not sure mi6 should have "build-readme" command.
And I want to keep mi6 having the same interface of perl5 minilla/milla.

**Comment by Skarsnik** [comment]
I am not sure it's a good behavior to force a rebuild of the Readme.md when simply running tests. Maybe some users does not want to generate the Readme.md from pod but still use mi6 for other task.

**Comment by azawawi** [comment]
@Skarsnik  I agree The regeneration of Readme.md is not a good side effect. `mi6 build` should be like `make` and should not have side-effects on source code. I disabled its support after adding it in [Atom Perl 6 Editor Tools](https://github.com/azawawi/atom-perl6-editor-tools/releases/tag/v0.9.18) because of this behavior. `build` should be something like syntax checking the whole project or running `panda-build`.

**Comment by ufobat** [comment]
I strongly agree that regenerating the README.md is not a expected/good side effect. For every CPAN release i've make I need to revert the changes to README.md and rebuild my tar manually,

**Comment by Skarsnik** [comment]
Hm, I am not entirely convinced that this close this issue. I wanted to redo the README without rebuilding everything.

**Comment by skaji** [comment]
I decided not to implement build-readme command.

**Pull request closed without merging**
