### PR TITLE
Tweak test.yml and .gitignore (templates and actual files)

### PR DESCRIPTION
**Pull request by japhb**
There are a couple changes I always make to the template files, and it occurs to me they appear generally useful, so are probably worth merging back to the mi6 core.  I also tweaked the actual files in the mi6 tree to match the updated templates.

### CODE REVIEW

**Comment by skaji** [comment]
@japhb  Thanks for your PR.

I think the primary purpose of this PR is to add "zef update" step to the github workflow file.
But I think it is automatically done by "zef install --deps-only ...".

**Comment by japhb** [comment]
Yes, `zef update` is implied by `zef install` when there is no cache yet (or the cache is old, but that doesn't apply here).  However, the output can get mixed together, making it a bit irritating when reviewing failed workflow runs.  So I make it a separate step, partially so I'm only looking at what failed, partially so it's super clear whether the failure was in caching the ecosystem data, or satisfying dependencies, or what have you.

Similarly, adding `-v` to the prove6 command line is also to make it easier to see what failed during test runs, to reduce the number of pushes it takes me to debug a problem on an OS that I don't have personally available.

The `.gitignore` additions are there because users of several common editors (Comma, Emacs, etc.) and upload tools (e.g. `fez`) will always want to add those patterns anyway; might as well do it when creating the skeleton.

**Comment by japhb** [comment]
Hey there!  Just wanted to know if you'd had a chance to consider my reply.  :-)

**Comment by japhb** [comment]
Ping?  :-)

**Comment by japhb** [comment]
Ping again  :-)

**Comment by skaji** [comment]
As I said, updating index is automatically done in "zef install --deps-only ..." step.
And other changes do not seem to be related to general Raku distributions.

So close this PR.

**Pull request closed without merging**
