### PR TITLE
Add Appveyor template and README badge

### PR DESCRIPTION
**Pull request by softmoth**
This makes it easy to set up Windows CI testing

### CODE REVIEW

**Comment by skaji** [comment]
Thanks.

* For adding Appveyor template: I'm now thinking about switching the default CI files to github actions.
* For configuring badges by dist.ini: I agree.

Let me think about it.

**Comment by skaji** [comment]
@softmoth I'd appreciate it if you could try #90 with the following config:
```ini
[Badges]
provider = appveyor
```

**Comment by softmoth** [comment]
It works well.

**Comment by skaji** [comment]
@softmoth thanks!

**Pull request closed without merging**
