### PR TITLE
Fix a license duration 2000-2015 -> 2000-2016

### PR DESCRIPTION
**Pull request by okaoka**
Hi.
I fixed a license duration, because the present year is 2016.

### CODE REVIEW

**Comment by skaji** [comment]
thanks!
Because the license file is just copied/pasted  from the rakudo one, why don't you raise a pull request for rakudo first?
https://github.com/rakudo/rakudo/blob/nom/LICENSE

**Comment by okaoka** [comment]
Thank you for your advise. 

> why don't you raise a pull request for rakudo first?

I see.
Then I'll send PR to that repository first.

**Comment by okaoka** [comment]
My pull request of fixing license duration was merged into rakudo.
https://github.com/rakudo/rakudo/commit/7010f322c28d53a53f92ca9d4110bf5ac8694227

**Comment by skaji** [comment]
:+1:

**Pull request merged**
