### PR TITLE
Add documentation on format of .pause

### PR DESCRIPTION
**Pull request by jmaslak**
I think this is valid documentation for #44 .  Something similar probably should be added to CPAN::Uploader::Tiny too.

### CODE REVIEW

**Comment by skaji** [comment]
Thanks!
Could you add a note that
pause files may be encrypted by gpg?

**Comment by jmaslak** [comment]
Yes, I think I can do that.  I'll update this PR.

**Comment by jmaslak** [comment]
I'm not a GPG expert but I think I added at least some pointers about encryption now to that section.

**Comment by skaji** [comment]
@jmaslak Thanks!

Note: Because pause files can be encrypted as binary format, I modified pod in 90719de.

**Comment by jmaslak** [comment]
Thanks - I missed that when reading the code in CPAN::Uploader::Tiny - but yep, I'm sure your right!

**Pull request merged**
