### PR TITLE
 mi6 now searches for pod ... 

### PR DESCRIPTION
**Pull request by holli-holzer**
not only in ./lib/Module/Name.pm6 but also in ./README.pod6, ./docs/Module/Name.pod6 and ./lib/Module/Name.pod6

### CODE REVIEW

**Comment by skaji** [comment]
What motivates you to do this?

**Comment by holli-holzer** [comment]
I want to make something I want to use better. Why are you asking?

**Comment by skaji** [comment]
If you want to change a file that generates README.md, then you can use dist.ini.
So I don't think mi6 needs to change current behavior.

**Comment by holli-holzer** [comment]
The current behaviour surprised me and probably more importantly, the experienced zoffixnet. Especially since the program doesnt warn if it finds nothing and silently overwrite the - maybe (*cough*) hand written - readme. What's wrong with letting the program look in all the usual places?

**Comment by skaji** [comment]
Thank you for explaining your motivation.

I don't think mi6 should search other files to generate README.md.
But, yeah, it could be nice emitting warnings when the main module file does not contain pod.

**Comment by holli-holzer** [comment]
https://irclog.perlgeek.de/perl6/2017-10-19#i_15324549

Arguments from authority suck, I know. Look, my change is well written, valueable and doesn't break anything. I don't understand why you are so reluctant. But fine, i will then just keep using Ddt.

**Comment by GeJ** [comment]
Beauty is in the eye of the beholder. Your coding style doesn't match the one of the author.
Also if I understand correctly this change will pick any existing 'README.pod6' over a file explicitly defined in `dist.ini` which looks like a POLA violation. The `.subst('lib', 'docs')` looks fragile and, while convoluted as it's the last possible choice in the list, one could think of a case where a file defined in dist.ini doesn't reside in 'lib/' but still has a "lib" sub-string in its name. Best case the resulting file doesn't exist, worst case it picks a totally unrelated file.
And finally, I like the minimalist approach of `mi6` with a simple behavior based on simple conventions and that it doesn't try too hard to do everything for everyone. In that regard `ddt` looks like an awesome tool that could easily be extended for custom workflows. But they clearly aim for different users with different needs.
Just sayin'

**Comment by holli-holzer** [comment]
True, that subst would better use a /^lib/ instead of 'lib', but that's a
minor point. And I wasn't aware there is an ini before skaji mentioned it.
This is also trivial to account for.

Regarding the style, I am quite happy my code doesn't look like i'd have to
pay line tax :-) Other than that I don't see any major differences in style?

**Pull request closed without merging**
